import { Bowman } from "./Character";
import { characters } from "./characters";

const user = new Bowman("user");
// user.health = 1;
// user.levelUp();
// user.health = 1;
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
// user.damage(10);
user.damage(10);
// user.levelUp();
console.log(user);
console.log(characters);